-- Primex Properties base schema. Run once in Supabase SQL Editor for the app's project.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  phone text,
  avatar_url text,
  role text not null default 'customer' check (role in ('super_admin','admin','sales_manager','sales_agent','content_manager','customer')),
  created_at timestamptz not null default now()
);

create table if not exists public.developers (
  id bigint generated by default as identity primary key, name text not null, slug text unique,
  logo text, logo_url text, cover_image text, description text, hq text, rating numeric,
  founded_year integer, projects_delivered integer, ongoing_projects integer,
  featured boolean not null default false, website text, phone text, email text,
  created_at timestamptz not null default now()
);
create table if not exists public.projects (
  id bigint generated by default as identity primary key, developer_id bigint references public.developers(id) on delete set null,
  name text not null, slug text unique, city text, locality text, address text, description text,
  cover_image text, gallery jsonb not null default '[]', status text, rera_number text, rera_status text,
  price_min numeric, price_max numeric, configurations text, total_units integer, tower_count integer,
  possession_date text, amenities jsonb not null default '[]', amenities_text text,
  featured boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.properties (
  id bigint generated by default as identity primary key, developer_id bigint references public.developers(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null, title text not null, slug text unique,
  city text, locality text, address text, description text, property_type text, listing_type text,
  status text, furnishing text, price numeric, price_per_sqft numeric, area_sqft numeric, carpet_note text,
  bedrooms integer, bathrooms integer, balconies integer, floor_no text, total_floors integer,
  facing text, parking text, video_url text, possession_date text, rera_number text, rera_approved boolean not null default false,
  cover_image text, featured boolean not null default false, is_active boolean not null default true,
  views integer not null default 0, created_at timestamptz not null default now()
);
create table if not exists public.amenities (
  id bigint generated by default as identity primary key, name text not null unique, icon text, category text
);
create table if not exists public.property_amenities (
  property_id bigint not null references public.properties(id) on delete cascade,
  amenity_id bigint not null references public.amenities(id) on delete cascade,
  primary key (property_id, amenity_id)
);
create table if not exists public.property_images (
  id bigint generated by default as identity primary key, property_id bigint not null references public.properties(id) on delete cascade,
  image_url text not null, caption text not null default '', sort_order integer not null default 0
);
create table if not exists public.leads (
  id bigint generated by default as identity primary key, property_id bigint references public.properties(id) on delete set null,
  project_id bigint references public.projects(id) on delete set null, name text not null, email text, phone text not null,
  source text, interest_type text, preferred_locality text, budget_min numeric, budget_max numeric,
  status text not null default 'New', message text, notes text, assigned_to text, follow_up_date date,
  score integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.site_visits (
  id bigint generated by default as identity primary key, lead_id bigint references public.leads(id) on delete set null,
  property_id bigint references public.properties(id) on delete set null, visitor_name text not null,
  visitor_phone text not null, visitor_email text, visit_date date not null, visit_time text,
  status text not null default 'Scheduled', agent text, notes text, created_at timestamptz not null default now()
);
create table if not exists public.favorites (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  created_at timestamptz not null default now(), unique(user_id, property_id)
);
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key, name text not null, locality text, rating integer,
  content text not null, avatar_url text, approved boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key, title text not null, slug text unique not null,
  excerpt text, content text, category text, cover_image text, author text, tags text,
  published boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.seo_pages (
  id bigint generated by default as identity primary key, slug text unique not null, title text not null,
  meta_description text, keywords text, h1 text, body text, created_at timestamptz not null default now()
);
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key, event_type text not null, property_id bigint references public.properties(id) on delete set null,
  page text, meta jsonb not null default '{}', created_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key, actor_user_id uuid, actor_email text,
  actor_role text, action text, entity text, entity_id text, meta jsonb,
  ip text, created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('property-media', 'property-media', true)
on conflict (id) do update set public = excluded.public;

-- API routes use the server-only service role key; keep direct browser access disabled.
alter table public.profiles enable row level security;
alter table public.developers enable row level security;
alter table public.projects enable row level security;
alter table public.properties enable row level security;
alter table public.amenities enable row level security;
alter table public.property_amenities enable row level security;
alter table public.property_images enable row level security;
alter table public.leads enable row level security;
alter table public.site_visits enable row level security;
alter table public.favorites enable row level security;
alter table public.testimonials enable row level security;
alter table public.blog_posts enable row level security;
alter table public.seo_pages enable row level security;
alter table public.analytics_events enable row level security;
alter table public.audit_logs enable row level security;
